= [WIP] OhMyDomains: An API and CLI to help you manage domain names with ease.

== Why?

When your domain names are scattered around registrars,
maintaining them becomes a pain.
Even remembering how many domain names you have and what they are
is no easy thing.

`OhMyDomains` aims to help you: with one API you can
retrieve data of any and all domain names you have,
and update their contact and name server records with ease.

It will support more registrars and functionalities, gradually.

== Install

`$ poetry add ohmydomains`

Or, the old way:

`$ pip install ohmydomains`

Or, install "only" the CLI, using https://github.com/pipxproject/pipx:[pipx]:

`$ pipx install ohmydomains`

== Usage

=== API

[source,python]
----
from ohmydomains import Manager, providers

manager = Manager()
manager.add_accounts(
	providers.namecheap({
		'api_user': NAMECHEAP_API_USER,
		'api_key': NAMECHEAP_API_KEY,
		# ...
	}),
	providers.namesilo({ 'api_key': NAMESILO_API_KEY })
)

for domain in manager.iter_domains(expiring_in=233):
	print(domain.name, domain.creation, domain.expiry)
----

=== CLI

[source,shell]
----
$ omd accounts track namecheap api_user:ohmydomains api_key:xxxxxxxx
Testing credentials...
Account tracked.
$ omd accounts track name --testing
Please enter your credentials below.
username: ohmydomains-test
token: xxxxxxxx
Testing credentials...
Account tracked.
$ omd list
Retrieving data for domain #7
Done. 7 domain names in total.
name             account                         creation    expiry      auto_renew
---------------  ------------------------------  ----------  ----------  ------------
mwo.sh           NameCheap:ohmydomains           2019-04-25  2020-04-25  enabled
colorless.ink    NameCheap:ohmydomians           2019-10-16  2020-10-16  enabled
ohmy.domains     Name:ohmydomains-test(testing)  2019-10-29  2020-10-29  enabled
ohmydomains.com  Name:ohmydomains-test(testing)  2019-10-29  2020-10-29  enabled
ohmydomains.org  Name:ohmydomains-test(testing)  2019-10-29  2020-10-29  enabled
ohmydomains.net  Name:ohmydomains-test(testing)  2019-10-29  2020-10-29  enabled
ohmydomains.co   Name:ohmydomains-test(testing)  2019-10-29  2020-10-29  enabled
----


